import Link from 'next/link';

export default function Page() {
  return (
    <>
      <div className="rts-breadcrumb-area breadcrumb-bg bg_image"><div className="container"><div className="row align-items-center"><div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 breadcrumb-1"><h1 className="title">Our Service</h1></div><div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12"><div className="bread-tag"><span><Link href="/">Home</Link><span> / </span></span><span><span className="active">Our Service</span></span></div></div></div></div></div><div className="rts-service-area rts-section-gap bg-service-h2 ptb--120 mt--0"><div className="container"><div className="row"><div className="title-area service-h2"><span>Our Latest Services</span><h2 className="title">Service We Provide</h2></div></div><div className="row g-5 mt--10"><div className="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12"><div className="rts-single-service-h2 inner"><Link className="thumbnail" href="/service-details"><img src="/assets/images/service/10.jpg" alt="Service_image" /></Link><div className="body"><Link href="/service-details"><h5 className="title">Business Solution</h5></Link><p className="disc">Fusce dignissim erat dis proin ornare class sem nibh</p><Link className="btn-red-more" href="/service-details">Learn More<i className="fas fa-arrow-right"></i></Link></div></div></div><div className="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12"><div className="rts-single-service-h2 inner"><Link className="thumbnail" href="/service-details"><img src="/assets/images/service/11.jpg" alt="Service_image" /></Link><div className="body"><Link href="/service-details"><h5 className="title">Creative Ideas</h5></Link><p className="disc">Fusce dignissim erat dis proin ornare class sem nibh</p><Link className="btn-red-more" href="/service-details">Learn More<i className="fas fa-arrow-right"></i></Link></div></div></div><div className="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12"><div className="rts-single-service-h2 inner"><Link className="thumbnail" href="/service-details"><img src="/assets/images/service/12.jpg" alt="Service_image" /></Link><div className="body"><Link href="/service-details"><h5 className="title">Market Research</h5></Link><p className="disc">Fusce dignissim erat dis proin ornare class sem nibh</p><Link className="btn-red-more" href="/service-details">Learn More<i className="fas fa-arrow-right"></i></Link></div></div></div><div className="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12"><div className="rts-single-service-h2 inner"><Link className="thumbnail" href="/service-details"><img src="/assets/images/service/13.jpg" alt="Service_image" /></Link><div className="body"><Link href="/service-details"><h5 className="title">Best Solution</h5></Link><p className="disc">Fusce dignissim erat dis proin ornare class sem nibh</p><Link className="btn-red-more" href="/service-details">Learn More<i className="fas fa-arrow-right"></i></Link></div></div></div></div></div></div><div></div>
    </>
  );
}
